% 1. Rede de Metro

%% 1. Rede de Metro
%%% Linhas
linha(1,['La Defense Grande Arche','Esplanade de la Defense','Pont de Neuilly','Les Sablons Jardin dAcclimatation','Porte Maillot Palais des Congres','Argentine','Charles de Gaulle - Etoile','George V','Franklin D. Roosevelt','Champs-Elysees - Clemenceau Grand Palais','Concorde','Tuileries','Palais Royal - Musee du Louvre','Louvre - Rivoli','Chatelet','Hotel de Ville','Saint-Paul Le Marais','Bastille','Gare de Lyon','Reuilly - Diderot','Nation','Porte de Vincennes','Saint-Mande','Berault','Chateau de Vincennes']).

linha(2,['Porte Dauphine – Marechal de Lattre de Tassigny','Victor Hugo','Charles de Gaulle - Etoile','Ternes','Courcelle','Moncea','Villiers','Rome','Place de Clichy','Blanch','Pigall','Anvers – Sacre Coeur','Barbes - Rochechouart','La Chapelle','Stalingrad','Jaures','Colonel Fabien','Belleville','Couronnes','Menilmontant','Pere Lachaise','Philippe Auguste','Alexandre Dumas','Avron','Nation']).

linha(3,['Pont de Levallois - Becon','Anatole France','Louise Michel','Porte de Champerret','Pereire','Marechal Juin','Wagram','Malesherbes','Villiers','Europe','Saint-Lazare','Havre - Caumartin','Opera','Quatre-Septembre','Bourse','Sentier','Reaumur - Sebastopol','Arts et Metiers','Temple','Republique','Parmentier','Rue Saint-Maur','Pere Lachaise	','Gambetta','Porte de Bagnolet','Gallieni']).

linha(4,['Porte de Clignancourt','Simplon','Marcadet - Poissonniers','Château Rouge','Barbes - Rochechouart','Gare du Nord','Gare de lEst Verdun','Château dEau','Strasbourg - Saint-Denis','Reaumur - Sebastopol','etienne Marcel','Les Halles','Châtelet','Cite','Saint-Michel','Odeon','Saint-Germain-des-Pres','Saint-Sulpice','Saint-Placide','Montparnasse - Bienvenue','Vavin','Raspail','Denfert-Rochereau Colonel Rol-Tanguy','Mouton-Duvernet','Alesia','Porte dOrleans – General Leclerc']).

linha(5, ['Bobigny - Pablo Picasso Prefecture - Hôtel du Departement','Bobigny - Pantin - Raymond Queneau','Eglise de Pantin','Hoche	Pantin','Porte de Pantin – Parc de la Villette','Ourcq','Laumiere','Jaures','Stalingrad','Gare du Nord','Gare de lEst – Verdun','Jacques Bonsergent','Republique','Oberkampf','Richard-Lenoir','Breguet - Sabin','Bastille','Quai de la Rapee','Gare dAusterlitz','Saint-Marcel','Campo-Formio','Place dItalie']).

linha(6,['Charles de Gaulle - Etoile','Kleber','Boissiere','Trocadero','Passy','Bir-Hakeim Tour Eiffel','Dupleix','La Motte-Picquet - Grenelle','Cambronne','Sevres - Lecourbe','Pasteur','Montparnasse - Bienvenue','Edgar Quinet','Raspail','Denfert-Rochereau','Saint-Jacques','Glaciere','Corvisart','Place dItalie','Nationale','Chevaleret','Quai de la Gare','Bercy','Dugommier','Daumesnil – Felix Eboue','Bel-Air','Picpus – Courteline','Nation']).

linha(7,['La Courneuve - 8 Mai 1945','Fort dAubervilliers','Aubervilliers - Pantin - Quatre Chemins','Porte de la Villette – Cite des Sciences et de lIndustrie','Corentin Cariou','Crimee','Riquet','Stalingrad','Louis Blanc','Chateau-Landon','Gare de lEst, Verdun','Poissonniere','Cadet','Le Peletier','Chaussee dAntin - La Fayette','Opera','Pyramides','Palais Royal - Musee du Louvre','Pont Neuf','Chatelet','Pont Marie – Cite des Arts','Sully - Morland','Jussieu','Place Monge Jardin des Plantes - Arenes de Lutece','Censier - Daubenton','Les Gobelins','Place dItalie','Tolbiac','Maison Blanche','Porte dItalie','Porte de Choisy','Porte dIvry','Pierre et Marie Curie','Mairie dIvry']).

linha(8,['Balard','Lourmel','Boucicaut','Felix Faure','Commerce','La Motte-Picquet - Grenelle','Ecole Militaire','La Tour-Maubourg','Invalides','Concorde','Madeleine','Opera','Richelieu - Drouot','Grands Boulevards','Bonne Nouvelle','Strasbourg - Saint-Denis','Republique','Filles du Calvaire','Saint-Sebastien - Froissart','Chemin Vert','Bastille','Ledru-Rollin','Faidherbe - Chaligny','Reuilly - Diderot','Montgallet','Daumesnil – Felix Eboue','Michel Bizot','Porte Doree','Porte de Charenton','Liberte','Charenton - Ecoles – Place Aristide Briand','Ecole Veterinaire de Maisons-Alfort','Maisons-Alfort - Stade','Maisons-Alfort - Les Juilliottes','Creteil - LEchat Hopital Henri Mondor','Creteil - Universite','Creteil - Prefecture Hotel de Ville']).

linha(9,['Pont de Sevres','Billancourt','Marcel Sembat','Porte de Saint-Cloud Parc des Princes','Exelmans','Michel-Ange - Molitor','Michel-Ange - Auteuil','Jasmin','Ranelagh','La Muette','Rue de la Pompe','Trocadero','Iena','Alma - Marceau','Franklin D Roosevelt','Saint-Philippe du Roule','Miromesnil','Saint-Augustin','Havre - Caumartin','Chaussee dAntin - La Fayette','Richelieu - Drouot','Grands Boulevards','Bonne Nouvelle','Strasbourg - Saint-Denis','Republique','Oberkampf','Saint-Ambroise','Voltaire – Leon Blum','Charonne','Rue des Boulets','Nation','Buzenval','Maraichers','Porte de Montreuil','Robespierre','Croix de Chavaux – Place Jacques Duclos','Mairie de Montreuil']).

linha(10,['Boulogne - Pont de Saint-Cloud Rhin et Danube','Boulogne - Jean Jaures','Porte dAuteuil','Michel-Ange - Molitor','Michel-Ange - Auteuil','Chardon-Lagache','eglise dAuteuil','Mirabeau','Javel - Andre Citroen','Charles Michels	','Avenue emile Zola','La Motte-Picquet - Grenelle	','Segur','Duroc','Vaneau','Sevres - Babylone','Mabillon','Odeon','Cluny - La Sorbonne','Maubert - Mutualite','Cardinal Lemoine','Jussieu','Gare dAusterlitz']).

linha(11,['Chatelet','Hotel de Ville','Rambuteau – Centre Georges Pompidou','Arts et Metiers','Republique','Goncourt – Hopital Saint-Louis','Belleville','Pyrenees','Jourdain','Place des Fetes','Telegraphe','Porte des Lilas','Mairie des Lilas']).

linha(12,['Porte de la Chapelle','Marx Dormoy','Marcadet - Poissonniers','Jules Joffrin','Lamarck - Caulaincourt','Abbesses – Butte Montmartre','Pigalle','Saint-Georges','Notre-Dame-de-Lorette','Trinite - dEstienne dOrves','Saint-Lazare','Madeleine','Concorde','Assemblee nationale','Solferino – Musee dOrsay','Rue du Bac','Sevres - Babylone','Rennes','Notre-Dame-des-Champs','Montparnasse - Bienvenue','Falguiere','Pasteur','Volontaires','Vaugirard – Adolphe Cherioux','Convention','Porte de Versailles Parc des Expositions de Paris','Corentin Celton','Mairie dIssy']).

linha(13,['Asnieres - Gennevilliers Les Courtilles','Les Agnettes','Gabriel Peri','Mairie de Clichy','Porte de Clichy','Brochant','La Fourche','Place de Clichy','Liege','Saint-Lazare','Miromesnil','Champs-elysees - Clemenceau Grand Palais','Invalides','Varenne','Saint-François-Xavier','Duroc','Montparnasse - Bienvenue','Gaite','Pernety','Plaisance','Porte de Vanves','Malakoff - Plateau de Vanves','Malakoff - Rue Etienne Dolet','Chatillon - Montrouge']).

linha(14, ['Saint-Lazare','Madeleine','Pyramides','Châtelet','Gare de Lyon','Bercy','Cour Saint-emilion','Bibliotheque François Mitterrand','Olympiades']).
